tradehook/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from rest_framework_nested import routers
from django.contrib.auth.decorators import login_required
from django.urls import path
from django.views.decorators.csrf import csrf_protect
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import views

# registering backend endpoints.
router = routers.DefaultRouter()
router.register('users',views.UserViewSet,basename='users')
router.register('api_keys',views.APIKeysViewSet,basename='api_keys')
router.register('event_logs',views.EventLogViewSet,basename='event_logs')
router.register('brokers',views.BrokerViewSet,basename='brokers')
router.register('customer_brokers',views.CustomerBrokersViewSet,basename='customer_brokers')

users_router = routers.NestedDefaultRouter(
    router,'users',lookup='user'
    )
api_keys_router = routers.NestedDefaultRouter(
    router,'api_keys',lookup='api_key'
    )
event_logs_router = routers.NestedDefaultRouter(
    router,'event_logs',lookup='event_log'
    )
brokers_router = routers.NestedDefaultRouter(
    router,'brokers',lookup='broker'
    )
customer_brokers_router = routers.NestedDefaultRouter(
    router,'customer_brokers',lookup='customer_broker'
)


# registering frontend endpoints
urlpatterns = [path('webhook/', views.webhook_receiver, name='webhook-receiver'),
               
               path('home/', views.home_page,name='home-page'),
               
               path('me/',csrf_protect(login_required(views.MeView.as_view())),name='me'),
               path('brokers/', views.brokers_list, name='brokers-list'),
               path('api-keys/', csrf_protect(login_required(views.APIKeyView.as_view())), name='api-keys'),
               path('event-logs/', csrf_protect(login_required(views.EventLogView.as_view())), name='event-logs'),
               path('account/', csrf_protect(login_required(views.account)),name='account'),
               path('alert-guide/',csrf_protect(views.alert_guide),name='alert-guide'),
               path('register/', views.register, name='register'),
               #path('login/', LoginView.as_view(), name='login'),
               path('logout/', LogoutView.as_view(), name='logout'),
] 
urlpatterns += router.urls + api_keys_router.urls + event_logs_router.urls + brokers_router.urls + customer_brokers_router.urls + users_router.urls 
urlpatterns += staticfiles_urlpatterns()

tradehook/models.py
import uuid
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager
from django.utils import timezone   

# Custom User manager to define required information to create user and superuser
class CustomerAccountManager(BaseUserManager):

    def create_user(self,email,username,first_name,last_name,password,**other_fields):

        email = self.normalize_email(email)
        user = self.model(email=email,username=username,first_name=first_name,last_name=last_name,**other_fields)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, username, first_name, last_name, password, **other_fields):

        other_fields.setdefault('is_staff', True)
        other_fields.setdefault('is_superuser', True)
        other_fields.setdefault('is_active', True)

        if other_fields.get('is_staff') is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if other_fields.get('is_superuser') is not True:
            raise ValueError("Superuser must have is_superuser=True.")

        return self.create_user(email, username, first_name, last_name, password, **other_fields)

# Custom user class.
class User(AbstractBaseUser, PermissionsMixin):
    
    # Cannot have two accounts with the same email.
    email = models.EmailField(unique=True)
    username = models.CharField(max_length=255)
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    start_date = models.DateTimeField(auto_now_add=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    password = models.CharField(max_length=255)
    objects = CustomerAccountManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username','first_name','last_name']

    def __str__(self) -> str:
        return self.username

class CustomerBrokers(models.Model):
    # All current and future brokers will be heres
    ALPACA = 'Alpaca'
    ALPACA_PAPER = 'Alpaca - Paper'
    #OANDA = 'Oanda'
    #TRADESTATION = 'Tradestation'

    # Defines available brokers
    MEMBERSHIP_CHOICES = [
        (ALPACA, 'Alpaca'),
        (ALPACA_PAPER, 'Alpaca - Paper'),
        #(OANDA, 'Oanda'),
        #(TRADESTATION, 'Tradestation'),
    ]

    # CustomerBroker objects are attached to users, upon deleting user, customerbroker object is also deleted
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    broker_name = models.CharField(
        max_length=255, choices=MEMBERSHIP_CHOICES)
   
    broker_api_key = models.CharField(max_length=255)

    # Some brokers may only provide one api key so the secret key is optional. 
    broker_secret_key = models.CharField(max_length=255, null=True, blank=True)

    # A user can only have one of each broker.
    class Meta:
        unique_together = ('user', 'broker_name')
    
class APIKeys(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    tradehook_api_key = models.UUIDField(default=uuid.uuid4, unique=True)

class EventLog(models.Model):

    user = models.ForeignKey(User,on_delete=models.CASCADE)
    received_at = models.DateTimeField(default=timezone.now)

    # Both webhook_data and broker_response are model fields that will be filled by post requests from other servers.
    webhook_data = models.JSONField()
    broker_response = models.JSONField()

class Broker(models.Model):

    slug = models.SlugField()
    broker_name = models.CharField(max_length=255)
    description = models.TextField(null=True,blank=True)

tradehook/forms.py
from django import forms
from .models import *
from django.contrib.auth.forms import UserCreationForm

# Custom user creation form.
class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('first_name','last_name','username', 'email', 'password1')

# Form for user to create a Customer Broker model object.
class CustomerBrokerForm(forms.ModelForm):
    class Meta:
        model = CustomerBrokers
        fields = ['broker_name', 'broker_api_key', 'broker_secret_key']
        
# Form for user to generate a TradeHook API Key
class APIKeyForm(forms.ModelForm):
    class Meta:
        model = APIKeys
        fields = ['tradehook_api_key']

class APIKeyManagementForm(forms.Form):
    generate_api_key = forms.BooleanField(required=False, widget=forms.CheckboxInput(attrs={'class': 'generate-button'}))
    delete_api_key = forms.BooleanField(required=False, widget=forms.CheckboxInput(attrs={'class': 'delete-button'}))

tradehook/views.py
import json
from .broker_apis import alpaca_orders
from django.http import HttpResponseBadRequest
from django.shortcuts import render, redirect
from django.views import View
from rest_framework.mixins import ListModelMixin, DestroyModelMixin, RetrieveModelMixin
from rest_framework.response import Response
from rest_framework.permissions import IsAdminUser
from rest_framework.viewsets import ModelViewSet, GenericViewSet
from django.contrib.auth import login
from django.conf import settings
from rest_framework import status
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from rest_framework.decorators import api_view
import alpaca_trade_api as alpaca
from .models import *
from .permissions import *
from .forms import *
from .serializers import *
from.pagination import *

ALPACA_API_BASE_URL = "https://paper-api.alpaca.markets"
ALPACA_LIVE_URL = "https://api.alpaca.markets"

#___________________________________________________________________________________________________________________________________________#
# Backend ViewSets

class UserViewSet(ModelViewSet):

    # loads all users to be viewed if authenticated user is an admin. ModelViewSet also allows for modifying, creating, and deleting model objects.
    queryset = User.objects.all()
    serializer_class = UserSerializer
    permission_classes = [IsAdminUser]
    pagination_class = CustomPagination

class CustomerBrokersViewSet(ModelViewSet):
    
   
    serializer_class = CustomerBrokersSerializer
    permission_classes = [IsAdminUser]
    pagination_class = CustomPagination
    queryset = CustomerBrokers.objects.all()

    # Custom CustomerBroker creation method
    def create(self, request, *args, **kwargs):
        # gets the user id
        user_id = request.data.get('user_id')
        # gets the broker name
        broker_name = request.data.get('broker_name')
        # Check if the user already has a CustomerBroker object with the same broker_name
        if CustomerBrokers.objects.filter(user_id=user_id, broker_name=broker_name).exists():
            return Response({'error': f'A CustomerBrokers object with the broker_name "{broker_name}" already exists for this customer.'}, status=status.HTTP_400_BAD_REQUEST)

        # If user does not have duplicate object, check if information is valid and create.
        serializer = CustomerBrokersSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    
    
class APIKeysViewSet(ModelViewSet):
    
    serializer_class = APIKeysSerializer
    permission_classes = [IsAdminUser]
    pagination_class = CustomPagination
    queryset = APIKeys.objects.all()

    # Custom APIKey creation method
    def create(self, request, *args, **kwargs):
        # same as before, get user id
        user_id = request.data.get('user_id')

        # Check if the user already has a TradeHook api key already
        if APIKeys.objects.filter(user_id=user_id).exists():
            return Response({'error': f'A Tradehook API key already exists for this user.'}, status=status.HTTP_400_BAD_REQUEST)

        # if not then create.
        serializer = APIKeysSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

class EventLogViewSet(DestroyModelMixin,ListModelMixin,RetrieveModelMixin,GenericViewSet):

    serializer_class = EventLogSerializer
    permission_classes = [IsAdminUser]
    pagination_class = CustomPagination
    queryset = EventLog.objects.all()
    

class BrokerViewSet(ListModelMixin,DestroyModelMixin,RetrieveModelMixin,GenericViewSet):

    serializer_class = BrokerSerializer
    pagination_class = CustomPagination
    permission_classes = [IsAdminOrReadOnly]
    queryset = Broker.objects.all()
    

    def create(self, request, *args, **kwargs):

        serializer = BrokerSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    

#___________________________________________________________________________________________________________________________________________#
# Frontend Views

# Custom registration view.
def register(request):
    if request.method == 'POST':
        # Check if user information is valid
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect(settings.LOGIN_REDIRECT_URL)
            
    else:
        form = UserRegistrationForm()

    # Customize the labels
    form.fields['first_name'].label = "First Name"
    form.fields['last_name'].label = "Last Name"
    form.fields['username'].label = "Username"
    form.fields['email'].label = "Email"
    form.fields['password1'].label = "Password"
    form.fields['password2'].label = "Password Confirmation"

    # render custom registration page.
    return render(request, 'registration/register.html', {'form': form})

# render home page with total webhook count. for fun
def home_page(request):
    webhook_count = EventLog.objects.all().count()
    return render(request,'home.html', {'webhook_count': webhook_count})

# render current broker list
def brokers_list(request):
    brokers = Broker.objects.all()
    return render(request, 'brokers_list.html', {'brokers': brokers})

def account(request):
    return render(request,'setup_guide.html')

def alert_guide(request):
    return render(request,'alert_guide.html')

# Custom View to see user profile
class MeView(View):

    # custom get method.
    def get(self,request,*args,**kwargs):
        # get the current user
        user = request.user
        # serializer current users data to be rendered in html.
        serializer = UserSerializer(user)
        return render(request, 'customer_profile.html', {'customer': serializer.data})
    
class EventLogView(View):
    
    # Custom get method for users Event Log
    def get(self, request, *args, **kwargs):
        user = request.user

        # if user has event log, retrieve it, else render nothing.
        try:
            event_logs = EventLog.objects.filter(user=user)
        except EventLog.DoesNotExist:
            event_logs = None

        context = {
            'event_logs': event_logs,
        }

        return render(request, 'event_logs.html', context)

# Custom View to render all API keys on one page. (Broker API Keys and TradeHook API key)
class APIKeyView(View):

        #
        # INSTEAD OF ERROR JSON RESPONSES, IMPLEMENT IN FRONTEND, JUST HIDE BUTTONS 
        #

    def get(self, request, *args, **kwargs):
        user = request.user

        # Query the APIKeys model to get the user's tradehook_api_key if it exists
        try:
            api_key = APIKeys.objects.get(user=user)
        except APIKeys.DoesNotExist:
            api_key = None

        # Query the CustomerBrokers model to get the user's brokers
        user_brokers = CustomerBrokers.objects.filter(user=user)

        # Pass the API key and user brokers to the template
        context = {
            'api_key': api_key,
            'user_brokers': user_brokers,
        }

        return render(request, 'api_keys.html', context)

    # custom post method for creating and deleting various API keys and brokers
    def post(self, request, *args, **kwargs):
        user = request.user

        # differentiate between generating and deleting for TradeHook API Key
        if request.POST.get('action') == 'generate':
            form = APIKeyForm(request.POST)


            # violates rule
            api_key, created = APIKeys.objects.get_or_create(user=user)

            # JUST HIDE THE GENERATE BUTTON INSTEAD OF STATUS ERROR AND JSONRESPONSE
            #if not created:
            #    return JsonResponse({'error': 'API key already exists.'}, status=400)
            
            # reload the page. 

            #return render(request, "api_keys.html", {'api_key': api_key})


            return redirect('https://tradehook-prod-fbb7997de66a.herokuapp.com/tradehook/api-keys/')
        
            
        elif request.POST.get('action') == 'delete':
            try:
                api_key = APIKeys.objects.get(user=user)
                api_key.delete()
                
                return redirect('https://tradehook-prod-fbb7997de66a.herokuapp.com/tradehook/api-keys/')
            # JUST HIDE THE DELETE BUTTON INSTEAD OF STATUS ERROR AND JSONRESPONSE
            except APIKeys.DoesNotExist:
                return redirect('https://tradehook-prod-fbb7997de66a.herokuapp.com/tradehook/api-keys/')
                #return JsonResponse({'error': 'API key not found.'}, status=404)
            
        # Handle the form submission to add a new broker
        elif request.POST.get('action') == 'add_broker':
        
            broker_form = CustomerBrokerForm(request.POST)
            try:
                if broker_form.is_valid():
                    broker = broker_form.save(commit=False)
                    broker.user = user
                    broker.save()
                    
                    return redirect('https://tradehook-prod-fbb7997de66a.herokuapp.com/tradehook/api-keys/')
                # JUST HIDE THE GENERATE BUTTON INSTEAD OF REDIRECT
            except:
                
                return redirect('https://tradehook-prod-fbb7997de66a.herokuapp.com/tradehook/api-keys/')
          
            
        elif request.POST.get('action') == 'delete_broker':
            broker_id = request.POST.get('broker_id')

tradehook/templates/api_keys.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="color-scheme" content="dark light">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <link rel="stylesheet" type="text/css" href="{% static 'tradehook/setup_guide.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'tradehook/home.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'tradehook/api_keys.css' %}">
    <title>API-Keys</title>
</head>
<body>
    <div class="background-color background-color-1"></div>
    <div class="background-color background-color-2"></div>
    <div class="background-color background-color-3"></div>
    <div class="background-color background-color-4"></div>
    <header>
        <div class="header-container">
            <div class="logo-title-container">
                <a href="https://tradehook-prod-fbb7997de66a.herokuapp.com/tradehook/home"><h1 id="logo-title">TradeHook</h1></a>
            </div>
            <nav>
                <ul class="links-list">
                    <li class="link-list-entry"><a href="https://tradehook-prod-fbb7997de66a.herokuapp.com/tradehook/account/" class="header-link"><h2>Account</h2></a></li>
                    <li class="link-list-entry"><a href="https://tradehook-prod-fbb7997de66a.herokuapp.com/tradehook/brokers/" class="header-link"><h2>Brokers</h2></a></li>
                    <li class="link-list-entry"><a href="https://tradehook-prod-fbb7997de66a.herokuapp.com/tradehook/register/" class="header-link"><h2>Register</h2></a></li>
                    <li class="link-list-entry"><a href="https://tradehook-prod-fbb7997de66a.herokuapp.com/" class="header-link"><h2>Login</h2></a></li>   
                </ul>
            </nav>
        </div>
    </header>
    <main>
        <div class="main-container">
            <div class="sidebar-div">
                <nav class="sidebar-links-nav">
                    <ul class="sidebar-links-list">
                        <li class="sidebar-links-list-entry">Your Account</li>
                        <li class="sidebar-links-list-entry"><a id="setup-guide" href="https://tradehook-prod-fbb7997de66a.herokuapp.com/tradehook/account/"><svg
                            width="24"
                            height="24"
                            viewBox="0 0 24 24"
                            fill="none"
                            xmlns="http://www.w3.org/2000/svg"
                          >
                            <path
                              fill-rule="evenodd"
                              clip-rule="evenodd"
                              d="M4 9C4 11.9611 5.60879 14.5465 8 15.9297V15.9999C8 18.2091 9.79086 19.9999 12 19.9999C14.2091 19.9999 16 18.2091 16 15.9999V15.9297C18.3912 14.5465 20 11.9611 20 9C20 4.58172 16.4183 1 12 1C7.58172 1 4 4.58172 4 9ZM16 13.4722C17.2275 12.3736 18 10.777 18 9C18 5.68629 15.3137 3 12 3C8.68629 3 6 5.68629 6 9C6 10.777 6.7725 12.3736 8 13.4722L10 13.4713V16C10 17.1045 10.8954 17.9999 12 17.9999C13.1045 17.9999 14 17.1045 14 15.9999V13.4713L16 13.4722Z"
                              fill="currentColor"
                            />
                            <path
                              d="M10 21.0064V21C10.5883 21.3403 11.2714 21.5351 12 21.5351C12.7286 21.5351 13.4117 21.3403 14 21V21.0064C14 22.111 13.1046 23.0064 12 23.0064C10.8954 23.0064 10 22.111 10 21.0064Z"
                              fill="currentColor"
                            />
                          </svg>Setup Guide</a></li>
                        <li class="sidebar-links-list-entry"><a id="alert-guide" href="https://tradehook-prod-fbb7997de66a.herokuapp.com/tradehook/alert-guide"><svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M14 3V3.28988C16.8915 4.15043 19 6.82898 19 10V17H20V19H4V17H5V10C5 6.82898 7.10851 4.15043 10 3.28988V3C10 1.89543 10.8954 1 12 1C13.1046 1 14 1.89543 14 3ZM7 17H17V10C17 7.23858 14.7614 5 12 5C9.23858 5 7 7.23858 7 10V17ZM14 21V20H10V21C10 22.1046 10.8954 23 12 23C13.1046 23 14 22.1046 14 21Z" fill="currentColor" /></svg>Alert Guide</a></li>
                        <li class="sidebar-links-list-entry"><a id="event-log" href="https://tradehook-prod-fbb7997de66a.herokuapp.com/tradehook/event-logs"><svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M20 4H4C3.44771 4 3 4.44772 3 5V19C3 19.5523 3.44772 20 4 20H20C20.5523 20 21 19.5523 21 19V5C21 4.44771 20.5523 4 20 4ZM4 2C2.34315 2 1 3.34315 1 5V19C1 20.6569 2.34315 22 4 22H20C21.6569 22 23 20.6569 23 19V5C23 3.34315 21.6569 2 20 2H4ZM6 7H8V9H6V7ZM11 7C10.4477 7 10 7.44772 10 8C10 8.55228 10.4477 9 11 9H17C17.5523 9 18 8.55228 18 8C18 7.44772 17.5523 7 17 7H11ZM8 11H6V13H8V11ZM10 12C10 11.4477 10.4477 11 11 11H17C17.5523 11 18 11.4477 18 12C18 12.5523 17.5523 13 17 13H11C10.4477 13 10 12.5523 10 12ZM8 15H6V17H8V15ZM10 16C10 15.4477 10.4477 15 11 15H17C17.5523 15 18 15.4477 18 16C18 16.5523 17.5523 17 17 17H11C10.4477 17 10 16.5523 10 16Z" fill="currentColor" /></svg>Event Log</a></li>
                        <li class="sidebar-links-list-entry"><a id="api-keys" href="https://tradehook-prod-fbb7997de66a.herokuapp.com/tradehook/api-keys/"><svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M6 8C4.34315 8 3 9.34315 3 11V13C3 14.6569 4.34315 16 6 16C7.65685 16 9 14.6569 9 13H15V15H17V13H18V15H20V11H9C9 9.34315 7.65685 8 6 8ZM7 13V11C7 10.4477 6.55228 10 6 10C5.44772 10 5 10.4477 5 11V13C5 13.5523 5.44772 14 6 14C6.55228 14 7 13.5523 7 13Z" fill="currentColor" /></svg>API Keys</a></li>
                        <li class="sidebar-links-list-entry"><a id="profile" href="https://tradehook-prod-fbb7997de66a.herokuapp.com/tradehook/me"><svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M16 9C16 11.2091 14.2091 13 12 13C9.79086 13 8 11.2091 8 9C8 6.79086 9.79086 5 12 5C14.2091 5 16 6.79086 16 9ZM14 9C14 10.1046 13.1046 11 12 11C10.8954 11 10 10.1046 10 9C10 7.89543 10.8954 7 12 7C13.1046 7 14 7.89543 14 9Z" fill="currentColor" /><path fill-rule="evenodd" clip-rule="evenodd" d="M12 1C5.92487 1 1 5.92487 1 12C1 18.0751 5.92487 23 12 23C18.0751 23 23 18.0751 23 12C23 5.92487 18.0751 1 12 1ZM3 12C3 14.0902 3.71255 16.014 4.90798 17.5417C6.55245 15.3889 9.14627 14 12.0645 14C14.9448 14 17.5092 15.3531 19.1565 17.4583C20.313 15.9443 21 14.0524 21 12C21 7.02944 16.9706 3 12 3C7.02944 3 3 7.02944 3 12ZM12 21C9.84977 21 7.87565 20.2459 6.32767 18.9878C7.59352 17.1812 9.69106 16 12.0645 16C14.4084 16 16.4833 17.1521 17.7538 18.9209C16.1939 20.2191 14.1881 21 12 21Z" fill="currentColor" /></svg>Profile</a></li>
                        <li class="sidebar-links-list-entry"><a id="logout" href="https://tradehook-prod-fbb7997de66a.herokuapp.com/tradehook/logout"><svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M8.51428 20H4.51428C3.40971 20 2.51428 19.1046 2.51428 18V6C2.51428 4.89543 3.40971 4 4.51428 4H8.51428V6H4.51428V18H8.51428V20Z" fill="currentColor" /><path d="M13.8418 17.385L15.262 15.9768L11.3428 12.0242L20.4857 12.0242C21.038 12.0242 21.4857 11.5765 21.4857 11.0242C21.4857 10.4719 21.038 10.0242 20.4857 10.0242L11.3236 10.0242L15.304 6.0774L13.8958 4.6572L7.5049 10.9941L13.8418 17.385Z" fill="currentColor" /></svg>Logout</a></li>
                    </ul>
                </nav>
            </div>
            <div class="simple-info-container">
                <div class="tradehook-api-form-container">
                    <h3 id="api-key-title">TradeHook API Key</h3>
                    {% if api_key %}
                    <p class="apikey">{{ api_key.tradehook_api_key }}</p>
                    {% endif %}
                    <p class="disabled generate-warning">TradeHook API key already exists!</p>
                    <p class="disabled delete-warning">TradeHook API key does not exist!</p>
                    <form id="generate-delete-form" class="login-form" method="post">
                        <div class="form-group">
                            {% csrf_token %}
                            <label for="{{ form.tradehook_api_key.id_for_label }}"></label>
                            <button  class="generate" type="submit" name="action" value="generate">Generate</button>
                        </div>
                        <div class="form-group">
                            {% csrf_token %}
                            <label for="{{ form.tradehook_api_key.id_for_label }}"></label>
                            <button class="delete" type="submit" name="action" value="delete">Delete</button>
                        </div>
                    </form>
                </div>
                <div class="brokers-list">
                    <h3>Your Brokers</h3>
                    <ul id="broker-list">
                        {% for broker in user_brokers %}
                            <li class="brokers-list-entry">
                                <p class="broker-list-entry-info">
                                    <p class="broker-list-entry-info-name broker-p">Broker: {{ broker.broker_name }}</p>
                                    <p class="broker-list-entry-info-key broker-p">API Key: {{ broker.broker_api_key }}</p>
                                    <p class="broker-list-entry-info-secret broker-p">Secret Key: {{ broker.broker_secret_key }}</p>
                                </p>
                                <form method="POST" class="broker-form" action="https://tradehook-prod-fbb7997de66a.herokuapp.com/tradehook/api-keys/">
                                    {% csrf_token %}
                                    <input type="hidden" name="action" value="delete_broker">
                                    <input type="hidden" name="broker_id" value="{{ broker.id }}">
                                    <button type="submit">Delete</button>
                                </form>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
            <div id="form-container" class="add-broker-form-container">
                <h3 class="broker">Add a New Broker:</h3>
                <form id="broker-form" method="POST" action="https://tradehook-prod-fbb7997de66a.herokuapp.com/tradehook/api-keys/">
                    <div class="add-broker-form">
                        {% csrf_token %}
                        <input type="hidden" name="action" value="add_broker">
                         {{ broker_form.as_p }}
                        <label id="broker-name-text" for="id_broker_name">Broker name:</label>
                        <p class="disabled broker-generate-warning">Broker already exists!</p>
                        <select name="broker_name"  required id="id_broker_name">
                            <option>Select a Broker</option>
                            <option class="broker-option" value="Alpaca">Alpaca</option>
                            <option class="broker-option" value="Alpaca - Paper">Alpaca - Paper</option>
                        </select>
                        <div class="form-group">
                            {% csrf_token %}
                            <input type="text" name="broker_api_key" maxlength="255" required id="id_broker_api_key">
                            <label for="id_broker_api_key">Broker API Key</label>
                        </div>
                        <div class="form-group">
                            {% csrf_token %}
                            <input type="text" name="broker_secret_key" maxlength="255" required id="id_broker_secret_key">
                            <label for="id_broker_secret_key">Broker secret key:</label>
                        </div>
                        <button type="submit">Add Broker</button>
                    </div>
                </form>
            </div>
        </div>
    </main>
    <script src="{% static 'tradehook/apiKeys.js' %}"></script>
</body>
</html>